version: "3.8"

services:
  backend:
    build: ./backend
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./test-video:/app/test-video
    restart: always

  frontend:
    build: ./frontend
    container_name: react_app
    ports:
      - "3000:3000"
    restart: always

